### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by 3XistencE** [libretro/REminiscence#6]
RetroArch Android 32
OpenGl render
Flashback original PC floppy version (with copy protection)
Tested also on original PC CD-Rom version

[reproduce the problem]
loading core and/or content and/or from automatic playlist will lead to crash RetroArch on Android System (not tested on arch64 architecture).

[test done]
Tested with different versions of Flashback (CD, floppy, gog.com one etc...). Documentation doesn't say much about it except the files needed (obviously on the directory).
Same result: crash of RA, files added to playlist without problem automatically.
Tried to load different level1 files (all the extensions present) with the same result

[log?]
I can't find any log (or maybe i just don't know the location) about Reminiscence (maybe can be useful in order to understand if it's a Core problem or RA implementation)

**Comment by inactive123** [comment]
Does this still happen with latest nightlies?

**Comment by 3XistencE** [comment]
@inactive123 i confirm the problem is solved with the latest nightlies
Full working now on Android 32bit devices
